wandb:
    key: 
    project: "VietnameseSentimentAnalysis"
data:
    train_path: Data_preprocessed/Train.csv
    val_path: Data_preprocessed/Validation.csv
    num_labels: 16
model:
    pretrain: vinai/phobert-base
    config:
        problem_type: single_label_classification
        num_labels: 16
        use_cls: False
        classifier_input_length: 196608 # 256 (sequence length) * 768 (bert output size)
        hidden_size: 120
train:
    output_dir: "output"
    num_train_epochs: 30
    per_device_train_batch_size: 4
    gradient_accumulation_steps: 16
    per_device_eval_batch_size: 4
    learning_rate: 0.0005
    warmup_steps: 50
    weight_decay: 0.01
    logging_dir: "logs"
    logging_steps: 10
    eval_strategy: "steps"
    eval_steps: 100
    save_steps: 100
    save_total_limit: 3
    dataloader_num_workers: 4
    dataloader_prefetch_factor: 2
    report_to: "wandb"
    run_name: "phobert-cls"
    load_best_model_at_end: True
eval:
    metric: accuracy