model_name: "vinai/phobert-base"
num_labels: 12
save_pretrained_path: "./phobert-sentiment-analysis"
tokenizer_save_path: "./phobert-sentiment-analysis"
hub_model_name: "dgktrnh/phobert-sentiment-analysis"
project_name: "your_project_name"
learning_rate: 2e-5
batch_size: 16
warmup_steps: 200
weight_decay: 0.01
logging_dir: "logs"
logging_steps: 10
evaluation_strategy: "steps"
eval_steps: 100
save_steps: 100
save_total_limit: 3
dataloader_num_workers: 4
dataloader_prefetch_factor: 2
report_to: "wandb"
run_name: "phobert-cls_sentiments"
load_best_model_at_end: true
